 <?php if (!defined('BASEPATH')) exit('No direct script access allowed');

	class M_pegawai extends CI_Model
	{
		public function select_PenerimaDisposisi()
		{
			$lvl = $this->session->userdata('level');
			$unit = $this->session->userdata('unit');
			$jabatan = $this->session->userdata('jabatan');
			// if ($lvl < 3) {
			//     $lvl += 1;
			// } else {
			//     $lvl += 1;
			// }
			$q = $this->db
				->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat,telp, id_satuan_kerja, nama_unit, id_jabatan, jabatan')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id')
				->join('tb_satuan_kerja as sk', 'j.id_satuan_kerja = sk.id ', 'left')
				->join('tb_user as u', 'u.id_pegawai = p.id ', 'left')
				->where('u.id_grup > 3')
				->where("p.id != '" . $this->session->userdata('id') . "'")
				->order_by('nama_lengkap', 'asc');

			if ($jabatan == 'SEKRETARIS KEMENTERIAN PEMUDA DAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIRO PERENCANAAN DAN ORGANISASI' OR jabatan='KEPALA BIRO KEUANGAN DAN RUMAH TANGGA' OR jabatan='KEPALA BIRO HUMAS DAN HUKUM' OR jabatan='DIREKTUR LPDUK' OR jabatan='DIREKTUR RUMAH SAKIT OLAHRAGA NASIONAL' OR jabatan='INSPEKTUR'")
					->get();
			} elseif ($jabatan == 'MENTERI') {
				$q = $q->where("level<>1")
					->where("(level>=2 AND level <=3) OR jabatan='INSPEKTUR' OR jabatan='KEPALA SUBBAGIAN KEPROTOKOLAN' OR
					 jabatan='KEPALA SUBBAGIAN TU MENTERI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIRO PERENCANAAN DAN ORGANISASI') {
				$q = $q->where("jabatan='KEPALA BAGIAN PROGRAM DAN ANGGARAN' OR jabatan='KEPALA BAGIAN EVALUASI DAN PENILAIAN KINERJA' 
					OR jabatan='KEPALA BAGIAN SUMBER DAYA MANUSIA APARATUR' OR jabatan='KEPALA BAGIAN ORGANISASI, TATA LAKSANA DAN KERJASAMA'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PROGRAM DAN ANGGARAN') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PROGRAM DAN ANGGARAN KEOLAHRAGAAN' OR jabatan='KEPALA SUBBAGIAN PROGRAM DAN ANGGARAN KEPEMUDAAN'
					OR jabatan='KEPALA SUBBAGIAN PROGRAM DAN ANGGARAN PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN EVALUASI DAN PENILAIAN KINERJA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN EVALUASI DAN PENILAIAN KINERJA KEOLAHRAGAAN' OR jabatan='KEPALA SUBBAGIAN EVALUASI DAN PENILAIAN KINERJA KEPEMUDAAN'
					OR jabatan='KEPALA SUBBAGIAN EVALUASI DAN PENILAIAN KINERJA PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN SUMBER DAYA MANUSIA APARATUR') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN SUMBER DAYA APARATUR' OR jabatan='KEPALA SUBBAGIAN MUTASI DAN KEPANGKATAN SUMBER DAYA MANUSIA APARATUR'
					OR jabatan='KEPALA SUBBAGIAN PENGEMBANGAN SUMBER DAYA MANUSIA APARATUR'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN ORGANISASI, TATA LAKSANA DAN KERJASAMA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN ORGANISASI' OR jabatan='KEPALA SUBBAGIAN TATA LAKSANA' OR jabatan='KEPALA SUBBAGIAN KERJASAMA ANTAR LEMBAGA'")
					->get();
				//OR jabatan=''
			} elseif ($jabatan == 'KEPALA BIRO KEUANGAN DAN RUMAH TANGGA') {
				$q = $q->where("jabatan='KEPALA BAGIAN KEUANGAN' or jabatan='KEPALA BAGIAN VERIFIKASI PELAKSANAAN ANGGARAN' OR jabatan='KEPALA BAGIAN PERLENGKAPAN DAN PENGELOLAAN BARANG MILIK NEGARA'
					OR jabatan='KEPALA BAGIAN RUMAH TANGGA'")
					->get();
				//OR jabatan=''
			} elseif ($jabatan == 'KEPALA BAGIAN KEUANGAN') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN KAS DAN PEMBAYARAN' OR jabatan='KEPALA SUBBAGIAN AKUNTANSI DAN PELAPORAN' 
					OR jabatan='KEPALA SUBBAGIAN PENGELOLAAN PNBP'")
					->get();
				//OR jabatan=''
			} elseif ($jabatan == 'KEPALA BAGIAN VERIFIKASI PELAKSANAAN ANGGARAN') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN VERIFIKASI PELAKSANAAN ANGGARAN KEOLAHRAGAAN' OR jabatan='KEPALA SUBBAGIAN VERIFIKASI PELAKSANAAN ANGGARAN KEPEMUDAAN'
					OR jabatan='KEPALA SUBBAGIAN VERIFIKASI PELAKSANAAN ANGGARAN PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERLENGKAPAN DAN PENGELOLAAN BARANG MILIK NEGARA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN LAYANAN PENGADAAN' or jabatan='KEPALA SUBBAGIAN PENGELOLAAN BARANG MILIK NEGARA'
					or jabatan='KEPALA SUBBAGIAN PENGHAPUSAN DAN HIBAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN RUMAH TANGGA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN URUSAN DALAM' or jabatan='KEPALA SUBBAGIAN KEAMANAN DAN KETERTIBAN' 
					or jabatan='KEPALA SUBBAGIAN PERJALANAN DINAS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIRO HUMAS DAN HUKUM') {
				$q = $q->where("jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT' or jabatan='KEPALA BAGIAN SISTEM INFORMASI' or jabatan='KEPALA BAGIAN HUKUM'
					or jabatan='KEPALA BAGIAN TATA USAHA'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUBUNGAN MASYARAKAT') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PELIPUTAN DAN PUBLIKASI' or jabatan='KEPALA SUBBAGIAN DOKUMENTASI DAN PERPUSTAKAAN'
					or jabatan='KEPALA SUBBAGIAN KOMUNIKASI DAN KEMITRAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN SISTEM INFORMASI') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PENGEMBANGAN DAN KEAMANAN SISTEM INFORMASI' or jabatan='KEPALA SUBBAGIAN PENGELOLA INFORMASI'
					or jabatan='KEPALA SUBBAGIAN SISTEM JARINGAN DAN PIRANTI KERAS'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUKUM') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERATURAN PERUNDANG-UNDANGAN' or jabatan='KEPALA SUBBAGIAN PERJANJIAN HUKUM'
					or jabatan='KEPALA SUBBAGIAN LAYANAN HUKUM'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN TATA USAHA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERSURATAN DAN ARSIP' or jabatan='KEPALA SUBBAGIAN KEPROTOKOLAN' or jabatan='KEPALA SUBBAGIAN TU MENTERI'
					or jabatan='KEPALA SUBBAGIAN TU SESMEN' or jabatan='KEPALA SUBBAGIAN TU STAF AHLI'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PEMBERDAYAAN PEMUDA') {
				$q = $q->where("jabatan='SEKRETARIS DEPUTI BIDANG PEMBERDAYAAN PEMUDA' or jabatan='ASISTEN DEPUTI TENAGA DAN PENINGKATAN SUMBER DAYA PEMUDA'
					or jabatan='ASISTEN DEPUTI PENINGKATAN WAWASAN PEMUDA' or jabatan='ASISTEN DEPUTI PENINGKATAN KAPASITAS PEMUDA' or jabatan='ASISTEN DEPUTI PENINGKATAN IPTEK DAN IMTAK PEMUDA'
					or jabatan='ASISTEN DEPUTI PENINGKATAN KREATIVITAS PEMUDA'")
					->get();
			} elseif ($jabatan == 'SEKRETARIS DEPUTI BIDANG PEMBERDAYAAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP' or jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN' or jabatan='KEPALA SUBBAGIAN SUMBER DAYA MANUSIA APARATUR DAN ARSIP'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUBUNGAN MASYARAKAT') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN HUBUNGAN MASYARAKAT DAN SISTEM INFORMASI' or jabatan='KEPALA SUBBAGIAN HUKUM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI TENAGA DAN PENINGKATAN SUMBER DAYA PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PENGKAJIAN TENAGA DAN SUMBER DAYA PEMUDA' or jabatan='KEPALA BIDANG TENAGA KEPEMUDAAN FORMAL DAN NONFORMAL'
					or jabatan='KEPALA BIDANG TENAGA KEPEMUDAAN LAYANAN KHUSUS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGKAJIAN TENAGA DAN SUMBER DAYA PEMUDA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGKAJIAN TENAGA PEMUDA' or jabatan='KEPALA SUBBIDANG PENGKAJIAN SUMBER DAYA PEMUDA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG TENAGA KEPEMUDAAN FORMAL DAN NONFORMAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG FORMAL' or jabatan='KEPALA SUBBIDANG NONFORMAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG TENAGA KEPEMUDAAN LAYANAN KHUSUS') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG DIFABEL' or jabatan='KEPALA SUBBIDANG KEMAMPUAN KHUSUS'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN WAWASAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG WAWASAN POLITIK, PERTAHANAN DAN KEAMANAN' or jabatan='KEPALA BIDANG WAWASAN LINGKUNGAN STRATEGIS DAN PENCEGAHAN BAHAYA DESTRUKTIF'
					or jabatan='KEPALA BIDANG WAWASAN SOSIAL, BUDAYA DAN HUKUM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG WAWASAN POLITIK, PERTAHANAN DAN KEAMANAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG WAWASAN POLITIK DAN PERTAHANAN' or jabatan='KEPALA SUBBIDANG PERTAHANAN DAN KEAMANAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG WAWASAN LINGKUNGAN STRATEGIS DAN PENCEGAHAN BAHAYA DESTRUKTIF') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG WAWASAN LINGKUNGAN STRATEGIS' or jabatan='KEPALA SUBBIDANG PENCEGAHAN BAHAYA DESTRUKTIF'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG WAWASAN SOSIAL, BUDAYA DAN HUKUM') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG WAWASAN SOSIAL DAN BUDAYA' or jabatan='KEPALA SUBBIDANG WAWASAN HUKUM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN KAPASITAS PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PARIWISATA DAN KEMARITIMAN' or jabatan='KEPALA BIDANG INDUSTRI DAN KEMANDIRIAN EKONOMI'
					or jabatan='KEPALA BIDANG KEDAULATAN PANGAN, ENERGI DAN LINGKUNGAN HIDUP'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PARIWISATA DAN KEMARITIMAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PARIWISATA' or jabatan='KEPALA SUBBIDANG MARITIM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG INDUSTRI DAN KEMANDIRIAN EKONOMI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMAHAMAN INDUSTRI' or jabatan='KEPALA SUBBIDANG KEMANDIRIAN EKONOMI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEDAULATAN PANGAN, ENERGI DAN LINGKUNGAN HIDUP') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KEDAULATAN PANGAN DAN ENERGI' or jabatan='KEPALA SUBBIDANG LINGKUNGAN HIDUP'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN IPTEK DAN IMTAK PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PEMETAAN DAN PENELUSURAN IPTEK' or jabatan='KEPALA BIDANG PEMANFAATAN IPTEK'
					or jabatan='KEPALA SUBBIDANG PENGAMALAN IMTAK'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMETAAN DAN PENELUSURAN IPTEK') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENELUSURAN IPTEK' or jabatan='KEPALA SUBBIDANG PEMETAAN IPTEK")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMANFAATAN IPTEK') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG TEKNOLOGI TEPAT GUNA' or jabatan='KEPALA SUBBIDANG TEKNOLOGI INDUSTRI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGHAYATAN DAN PENGAMALAN IMTAK') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGHAYATAN IMTAK' or jabatan='KEPALA SUBBIDANG PENGAMALAN IMTAK'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN KREATIVITAS PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG KREATIVITAS GRAFIKA DAN KRIYA' or jabatan='KEPALA BIDANG KREATIVITAS FASHION DAN FILM'
					or jabatan='KEPALA BIDANG KREATIVITAS TEKNOLOGI INFORMASI' or jabatan='KEPALA BIDANG KREATIVITAS MUSIK DAN KULINER'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS GRAFIKA DAN KRIYA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG GRAFIKA' or jabatan='KEPALA SUBBIDANG KRIYA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS GRAFIKA DAN KRIYA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG GRAFIKA' or jabatan='KEPALA SUBBIDANG KRIYA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS FASHION DAN FILM') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG FASHION' or jabatan' or jabatan='KEPALA SUBBIDANG FILM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS TEKNOLOGI INFORMASI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PIRANTI LUNAK' or jabatan='KEPALA SUBBIDANG PERANGKAT KERAS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS MUSIK DAN KULINER') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG MUSIK' or jabatan='KEPALA SUBBIDANG KULINER'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PENGEMBANGAN PEMUDA') {
				$q = $q->where("jabatan='ASISTEN DEPUTI KEPEMINPINAN DAN KEPELOPORAN PEMUDA' or jabatan='ASISTEN DEPUTI KEWIRAUSAHAAN PEMUDA'
					or jabatan='ASISTEN DEPUTI ORGANISASI KEPEMUDAAN DAN KEPRAMUKAAN' or jabatan='ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR PEMUDA'
					or jabatan='ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA' or jabatan='SEKRETARIS DEPUTI BIDANG PENGEMBANGAN PEMUDA'")
					->get();
			} elseif ($jabatan == 'SEKRETARIS DEPUTI BIDANG PENGEMBANGAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP' or jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT, HUKUM, DAN SISTEM INFORMASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN' or jabatan='KEPALA SUBBAGIAN SUMBER DAYA MANUSIA APARATUR DAN ARSIP'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEPEMINPINAN DAN KEPELOPORAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG KADERISASI DAN PENDAYAGUNAAN KEPEMIMPINAN' or jabatan='KEPALA BIDANG KEPELOPORAN TANGGAP BENCANA DAN RAWAN SOSIAL'
					or jabatan='KEPALA BIDANG KEPELOPORAN DESA DAN DAERAH KHUSUS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KADERISASI DAN PENDAYAGUNAAN KEPEMIMPINAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KADERISASI' or jabatan='KEPALA SUBBIDANG PENDAYAGUNAAN KEPEMIMPINAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEPELOPORAN TANGGAP BENCANA DAN RAWAN SOSIAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG TANGGAP BENCANA' or jabatan='KEPALA SUBBIDANG RAWAN SOSIAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEPELOPORAN DESA DAN DAERAH KHUSUS') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN DESA' or jabatan='KEPALA SUBBIDANG DAERAH TERLUAR DAN TERTINGGAL'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEWIRAUSAHAAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PENELUSURAN DAN PEMETAAN POTENSI KEWIRAUSAHAAN PEMUDA' or jabatan='KEPALA BIDANG PENDAMPINGAN DAN PENGEMBANGAN POTENSI'
					or jabatan='KEPALA BIDANG AKSES PERMODALAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENELUSURAN DAN PEMETAAN POTENSI KEWIRAUSAHAAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENELUSURAN' or jabatan='KEPALA SUBBIDANG PEMETAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENDAMPINGAN DAN PENGEMBANGAN POTENSI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENDAMPINGAN' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN POTENSI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG AKSES PERMODALAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG FASILITAS PERMODALAN' or jabatan='KEPALA SUBBIDANG FASILITAS KELEMBAGAAN LPKP'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI ORGANISASI KEPEMUDAAN DAN KEPRAMUKAAN') {
				$q = $q->where("jabatan='KEPALA BIDANG ORGANISASI KEPELAJARAN' or jabatan='KEPALA BIDANG ORGANISASI KEMAHASISWAAN' 
					or jabatan='KEPALA BIDANG ORGANISASI KEPEMUDAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEPELAJARAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INTRA BIDANG ORGANISASI KEPELAJARAN' or jabatan='KEPALA SUBBAGIAN EXTRA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEMAHASISWAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INTRA BIDANG ORGANISASI KEMAHASISWAAN' or jabatan='KEPALA SUBBAGIAN EXTRA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEPEMUDAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INTRA BIDANG ORGANISASI KEPEMUDAAN' or jabatan='KEPALA SUBBAGIAN EXTRA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG STANDARISASI ORGANISASI DAN SARANA KEPEMUDAAN' or jabatan='KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TIMUR'
					or jabatan='KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TENGAH' or jabatan='KEPALA BIDANG PRASARANA DAN SARANA INDONESIA BARAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG STANDARISASI ORGANISASI DAN SARANA KEPEMUDAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PENDIDIKAN' or jabatan='KEPALA SUBBIDANG ORGANISASI KEPEMUDAAN'
					or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PRESTASI' or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA REKREASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TIMUR') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA INDONESIA TIMUR' or jabatan='KEPALA SUBBIDANG PRASARANA INDONESIA TIMUR'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TENGAH') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA INDONESIA TENGAH' or jabatan='KEPALA SUBBIDANG PRASARANA INDONESIA TENGAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA INDONESIA BARAT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA INDONESIA BARAT' or jabatan='KEPALA SUBBIDANG PRASARANA INDONESIA BARAT'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG KEMITRAAN DALAM NEGERI' or jabatan='KEPALA BIDANG KEMITRAAN LUAR NEGERI'
					or jabatan='KEPALA BIDANG PROMOSI DAN PENGHARGAAN KEPEMUDAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEMITRAAN DALAM NEGERI') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN KEMITRAAN PUSAT DAN DAERAH' or jabatan='KEPALA SUBBIDANG KEMITRAAN LINTAS SEKTOR DAN SWASTA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEMITRAAN LUAR NEGERI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG BILATERAL' or jabatan='KEPALA SUBBIDANG MULTILATERAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PROMOSI DAN PENGHARGAAN KEPEMUDAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PROMOSI KEPEMUDAAN' or jabatan='KEPALA SUBBIDANG PENGHARGAAN KEPEMUDAAN'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PEMBUDAYAAN OLAHRAGA') {
				$q = $q->where("jabatan='ASISTEN DEPUTI PENGELOLAAN OLAHRAGA PENDIDIKAN' or jabatan='ASISTEN DEPUTI PENGELOLAAN OLAHRAGA REKREASI'
					or jabatan='ASISTEN DEPUTI PENGELOLAAN PEMBINAAN SENTRA DAN SEKOLAH KHUSUS OLAHRAGA' or jabatan='ASISTEN DEPUTI PENGEMBANGAN OLAHRAGA TRADISIONAL DAN LAYANAN KHUSUS'
					or jabatan='ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGELOLAAN OLAHRAGA PENDIDIKAN') {
				$q = $q->where("jabatan='KEPALA BIDANG OLAHRAGA PENDIDIKAN DASAR' or jabatan='KEPALA BIDANG OLAHRAGA PENDIDIKAN MENENGAH'
					or jabatan='KEPALA BIDANG OLAHRAGA PENDIDIKAN TINGGI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENDIDIKAN DASAR') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN BIDANG OLAHRAGA PENDIDIKAN DASAR' or jabatan='KEPALA SUBBIDANG KOMPETISI BIDANG OLAHRAGA PENDIDIKAN DASAR'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENDIDIKAN MENENGAH') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN BIDANG OLAHRAGA PENDIDIKAN MENENGAH' or jabatan='KEPALA SUBBIDANG KOMPETISI BIDANG OLAHRAGA PENDIDIKAN MENENGAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENDIDIKAN TINGGI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN BIDANG OLAHRAGA PENDIDIKAN TINGGI' or jabatan='KEPALA SUBBIDANG KOMPETISI BIDANG OLAHRAGA PENDIDIKAN TINGGI'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGELOLAAN OLAHRAGA REKREASI') {
				$q = $q->where("jabatan='KEPALA BIDANG PEMBINAAN OLAHRAGA MASSAL DAN KESEHATAN OLAHRAGA' or jabatan='KEPALA BIDANG PENGEMBANGAN SANGGAR DAN PUSAT KEBUGARAN'
					or jabatan='KEPALA BIDANG PENGELOLAAN OLAHRAGA PETUALANGAN, TANTANGAN DAN WISATA' or jabatan='KEPALA BIDANG PENGEMBANGAN RUANG PUBLIK OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMBINAAN OLAHRAGA MASSAL DAN KESEHATAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN OLAHRAGA MASSAL' or jabatan='KEPALA SUBBIDANG KESEHATAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGEMBANGAN SANGGAR DAN PUSAT KEBUGARAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN SANGGAR OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PUSAT KEBUGARAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGELOLAAN OLAHRAGA PETUALANGAN, TANTANGAN DAN WISATA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN OLAHRAGA PETUALANGAN DAN TANTANGAN' or jabata='KEPALA SUBBIDANG PENGELOLAAN OLAHRAGA WISATA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGEMBANGAN RUANG PUBLIK OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN RUANG PUBLIK OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGKAJIAN RUANG PUBLIK OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGELOLAAN PEMBINAAN SENTRA DAN SEKOLAH KHUSUS OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG SENTRA DAN PERKUMPULAN OLAHRAGA' or jabatan='KEPALA BIDANG SEKOLAH KHUSUS OLAHRAGA'
					or jabatan='KEPALA BIDANG PEMBINAAN PPLP' or jabatan='KEPALA BIDANG PEMBINAAN PPLM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SENTRA DAN PERKUMPULAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN SENTRA DAN PERKUMPULAN OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN SENTRA DAN PERKUMPULAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SEKOLAH KHUSUS OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN SEKOLAH KHUSUS OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN SEKOLAH KHUSUS OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMBINAAN PPLP') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN PPLP' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PPLP'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMBINAAN PPLM') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN PPLM' or jabatan='KEPALA SUBBIDANG PEMBINAAN PPLM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGEMBANGAN OLAHRAGA TRADISIONAL DAN LAYANAN KHUSUS') {
				$q = $q->where("jabatan='KEPALA BIDANG OLAHRAGA TRADISIONAL' or jabatan='KEPALA BIDANG OLAHRAGA USIA DINI, LANJUT USIA DAN OLAHRAGA KHUSUS'
					or jabatan='KEPALA BIDANG OLAHRAGA PENYANDANG CACAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA TRADISIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGKAJIAN OLAHRAGA TRADISIONAL' or jabatan='KEPALA SUBBIDANG PENGELOLAAN OLAHRAGA TRADISIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA USIA DINI, LANJUT USIA DAN OLAHRAGA KHUSUS') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN OLAHRAGA USIA DINI DAN LANJUT USIA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN OLAHRAGA KHUSUS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENYANDANG CACAT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN OLAHRAGA PENYANDANG CACAT' or jabatan='KEPALA SUBBIDANG KOMPETISI OLAHRAGA PENYANDANG CACAT'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG KEMITRAAN DALAM NEGERI DAN LUAR NEGERI' or jabatan='KEPALA BIDANG BIMBINGAN DAN PENGEMBANGAN KARIER ATLIT'
					or jabatan='KEPALA BIDANG PENGHARGAAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEMITRAAN DALAM NEGERI DAN LUAR NEGERI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KEMITRAAN DALAM NEGERI' or jabatan='KEPALA SUBBIDANG KEMITRAAN LUAR NEGERI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG BIMBINGAN DAN PENGEMBANGAN KARIER ATLIT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG BIMBINGAN' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN KARIER'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGHARGAAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENELUSURAN PENGHARGAAN OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENYELENGGARAAN PENGHARGAAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PENINGKATAN PRESTASI OLAHRAGA') {
				$q = $q->where("jabatan='SEKRETARIS DEPUTI BIDANG PENINGKATAN PRESTASI OLAHRAGA' or jabatan='ASISTEN DEPUTI PEMBIBITAN DAN IPTEK OLAHRAGA'
					or jabatan='ASISTEN DEPUTI PENINGKATAN TENAGA DAN ORGANISASI KEOLAHRAGAAN' or jabatan='ASISTEN DEPUTI INDUSTRI DAN PROMOSI OLAHRAGA'
					or jabatan='ASISTEN DEPUTI OLAHRAGA PRESTASI' or jabatan='ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'SEKRETARIS DEPUTI BIDANG PENINGKATAN PRESTASI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP' or jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT, HUKUM, DAN SISTEM INFORMASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN' or jabatan='KEPALA SUBBAGIAN SUMBER DAYA MANUSIA APARATUR DAN ARSIP'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUBUNGAN MASYARAKAT, HUKUM, DAN SISTEM INFORMASI') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN HUBUNGAN MASYARAKAT DAN SISTEM INFORMASI' or jabatan='KEPALA SUBBAGIAN HUKUM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PEMBIBITAN DAN IPTEK OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG PEMANDUAN DAN PENGEMBANGAN BAKAT' or jabatan='KEPALA BIDANG KOMPETISI USIA MUDA'
					or jabatan='KEPALA BIDANG PENGEMBANGAN IPTEK OLAHRAGA' or jabatan='KEPALA BIDANG PEMANFAATAN IPTEK OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMANDUAN DAN PENGEMBANGAN BAKAT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMANDUAN BAKAT' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN BAKAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KOMPETISI USIA MUDA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KOMPETISI DAERAH DAN NASIONAL' or jabatan='KEPALA SUBBIDANG KOMPETISI INTERNASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGEMBANGAN IPTEK OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN ILMU PENGETAHUAN KEOLAHRAGAAN' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN TEKNOLOGI KEOLAHRAGAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMANFAATAN IPTEK OLAHRAGA') {
				$q = $q->where("jabatan='EPALA SUBBIDANG DISEMINASI' or jabatan='KEPALA SUBBIDANG PENERAPAN'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN TENAGA DAN ORGANISASI KEOLAHRAGAAN') {
				$q = $q->where("jabatan='KEPALA BIDANG PENINGKATAN MUTU PELATIH DAN INSTRUKTUR' or jabatan='KEPALA BIDANG PENINGKATAN MUTU WASIT, JURI DAN TENAGA PENDUKUNG'
					or jabatan='KEPALA BIDANG ORGANISASI KEOLAHRAGAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENINGKATAN MUTU PELATIH DAN INSTRUKTUR') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU PELATIH' or jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU INSTRUKTUR'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENINGKATAN MUTU WASIT, JURI DAN TENAGA PENDUKUNG') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU WASIT DAN JURI' or jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU TENAGA PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEOLAHRAGAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN INDUK ORGANISASI CABANG OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGELOLAAN ORGANISASI FUNGSIONAL DAN PROFESIONAL'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI INDUSTRI DAN PROMOSI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG PRODUK BARANG DAN JASA INDUSTRI OLAHRAGA' or jabatan='KEPALA SUBBIDANG INVENTARISASI INDUSTRI OLAHRAGA'
					or jabatan='KEPALA BIDANG PROMOSI DAN PEMASARAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRODUK BARANG DAN JASA INDUSTRI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PRODUK BARANG INDUSTRI OLAHRAGA' or jabatan='KEPALA SUBBIDANG PRODUK JASA INDUSTRI OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA SUBBIDANG INVENTARISASI INDUSTRI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INVENTARISASI INDUSTRI OLAHRAGA' or jabatan='KEPALA SUBBIDANG MANAJEMEN INDUSTRI OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PROMOSI DAN PEMASARAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PROMOSI OLAHRAGA' or jabatan='KEPALA SUBBIDANG PEMASARAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI OLAHRAGA PRESTASI') {
				$q = $q->where("jabatan='KEPALA BIDANG OLAHRAGA PRESTASI DAERAH' or jabatan='KEPALA BIDANG OLAHRAGA PRESTASI NASIONAL'
					or jabatan='KEPALA BIDANG OLAHRAGA PRESTASI INTERNASIONAL' or jabatan='KEPALA BIDANG PENGELOLAAN PEMUSATAN PELATIHAN OLAHRAGA NASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PRESTASI DAERAH') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN PRESTASI DAERAH' or jabatan='KEPALA SUBBIDANG PEKAN DAN KEJUARAAN OLAHRAGA PRESTASI DAERAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PRESTASI NASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEKAN DAN KEJUARAAN OLAHRAGA PRESTASI NASIONAL' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PRESTASI NASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PRESTASI INTERNASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEKAN DAN KEJUARAAN OLAHRAGA PRESTASI INTERNASIONAL' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PRESTASI INTERNASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGELOLAAN PEMUSATAN PELATIHAN OLAHRAGA NASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN ATLET ANDALAN NASIONAL' or jabatan='KEPALA SUBBIDANG TATA KELOLA KONTINGEN'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG STANDARISASI, AKREDITASI, DAN SERTIFIKASI KEOLAHRAGAAN' or jabatan='KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PENDIDIKAN'
					or jabatan='KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA REKREASI' or jabatan='KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PRESTASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG STANDARISASI, AKREDITASI, DAN SERTIFIKASI KEOLAHRAGAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG STANDARISASI' or jabatan='KEPALA SUBBIDANG AKREDITASI DAN SERTIFIKASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PENDIDIKAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PENDIDIKAN' or jabatan='KEPALA SUBBIDANG PRASARANA OLAHRAGA PENDIDIKAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA REKREASI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PRASARANA OLAHRAGA REKREASI' or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA REKREASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PRESTASI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PRASARANA OLAHRAGA PRESTASI' or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PRESTASI'")
					->get();
			// Mei 2020		
			}elseif ($jabatan == 'INSPEKTUR') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN TATA USAHA INSPEKTORAT'")
					->get();
			}elseif ($jabatan == 'KEPALA PUSAT PENGEMBANGAN ILMU PENGETAHUAN DAN TEKNOLOGI, DAN KESEHATAN OLAHRAGA NASIOANAL') {
				$q = $q->where("jabatan='KEPALA BAGIAN TATA USAHA' or jabatan='KEPALA BIDANG ANTROPOMETRI DAN KAPASITAS FISIK' or jabatan='KEPALA BIDANG BIOMEKANIK DAN KEBUGARAN JASMANI' or jabatan='KEPALA BIDANG KESEHATAN OLAHRAGAWAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN TATA USAHA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN KEPEGAWAIAN DAN KEUANGAN' or jabatan='KEPALA SUBBAGIAN UMUM'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG ANTROPOMETRI DAN KAPASITAS FISIK') {
				$q = $q->where("jabatan='KEPALA SEKSI ANTROPOMETRI DAN GIZI' or jabatan='KEPALA SEKSI KAPASITAS FISIK'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG BIOMEKANIK DAN KEBUGARAN JASMANI') {
				$q = $q->where("jabatan='KEPALA SEKSI BIOMEKANIK' or jabatan='KEPALA SEKSI KEBUGARAN JASMANI'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG KESEHATAN OLAHRAGAWAN') {
				$q = $q->where("jabatan='KEPALA SEKSI MEDIS' or jabatan='KEPALA SEKSI REHABILITASI DAN FISIOTERAPI'")
					->get();
			}elseif ($jabatan == 'KEPALA PPPON') {
				$q = $q->where("jabatan='KEPALA BAGIAN TU PPPON' or jabatan='KEPALA BIDANG PRASARANA DAN SARANA TEKNIS PPPON' or jabatan='KEPALA BIDANG PENYELENGGARAAN PEMUDA PPPON' or jabatan='KEPALA BIDANG PENYELENGGARAAN OLAHRAGA PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BAGIAN TU PPPON') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN UMUM DAN KEPEGAWAIAN PPPON' or jabatan='KEPALA SUBBAGIAN KEUANGAN DAN EVALUASI PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA TEKNIS PPPON') {
				$q = $q->where("jabatan='KEPALA SEKSI PRASARANA TEKNIS PPPON' or jabatan='KEPALA SEKSI SARANA TEKNIS PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG PENYELENGGARAAN PEMUDA PPPON') {
				$q = $q->where("jabatan='KEPALA SEKSI PROGRAM PPPON' or jabatan='KEPALA SEKSI EVALUASI PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG PENYELENGGARAAN OLAHRAGA PPPON') {
				$q = $q->where("jabatan='KEPALA SEKSI PROGRAM DAN EVALUASI PENYELENGGARAAN OLAHRAGA PPPON' or jabatan='KEPALA SEKSI SARANA TEKNIS PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA MUSEUM OLAHRAGA NASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN TATA USAHA' or jabatan='KEPALA SEKSI PAMERAN DAN EDUKASI' or jabatan='KEPALA SEKSI KOLEKSI DAN DOKUMENTASI'")
					->get();
			} else {
				$q = $q->get();
			}

			return $q->result_array();
		}
		public function selectPlh()
		{
			$lvl = $this->session->userdata('level');
			$level = $lvl + 1;
			//var_dump($lvl); die();
			$unit = $this->session->userdata('unit');
			$jabatan = $this->session->userdata('jabatan');
			//var_dump($jabatan); die();
			$q = $this->db
				->select('p.id,p.nip,p.nama_lengkap,p.nama_singkat,p.alamat,p.telp,
                p.jenis_kelamin,p.golongan,p.agama,p.tempat_lahir,p.tgl_lahir,j.id_satuan_kerja,
               p.id_jabatan,j.jabatan,p.level,p.idplh,sk.id as id_sk,sk.nama_unit')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'j.id=p.id_jabatan')
				->join('tb_satuan_kerja as sk', 'sk.id=j.id_satuan_kerja')
				->where("NOT (level = '0')")
				->where("p.level = " . $level . "");
			//->where("j.id_satuan_kerja =  '" . $unit . "'");

			if ($jabatan == 'SEKRETARIS KEMENTERIAN PEMUDA DAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIRO PERENCANAAN DAN ORGANISASI' OR jabatan='KEPALA BIRO KEUANGAN DAN RUMAH TANGGA' OR jabatan='KEPALA BIRO HUMAS DAN HUKUM'  OR jabatan='DIREKTUR LPDUK' OR jabatan='DIREKTUR RUMAH SAKIT OLAHRAGA NASIONAL' OR jabatan='INSPEKTUR'")
					->get();
			} elseif ($jabatan == 'MENTERI') {
				$q = $q->where("level<>1")
					->where("(level>=2 AND level <=3) OR jabatan='INSPEKTUR' OR jabatan='KEPALA SUBBAGIAN KEPROTOKOLAN' OR
					 jabatan='KEPALA SUBBAGIAN TU MENTERI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIRO PERENCANAAN DAN ORGANISASI') {
				$q = $q->where("jabatan='KEPALA BAGIAN PROGRAM DAN ANGGARAN' OR jabatan='KEPALA BAGIAN EVALUASI DAN PENILAIAN KINERJA' 
					OR jabatan='KEPALA BAGIAN SUMBER DAYA MANUSIA APARATUR' OR jabatan='KEPALA BAGIAN ORGANISASI, TATA LAKSANA DAN KERJASAMA'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PROGRAM DAN ANGGARAN') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PROGRAM DAN ANGGARAN KEOLAHRAGAAN' OR jabatan='KEPALA SUBBAGIAN PROGRAM DAN ANGGARAN KEPEMUDAAN'
					OR jabatan='KEPALA SUBBAGIAN PROGRAM DAN ANGGARAN PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN EVALUASI DAN PENILAIAN KINERJA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN EVALUASI DAN PENILAIAN KINERJA KEOLAHRAGAAN' OR jabatan='KEPALA SUBBAGIAN EVALUASI DAN PENILAIAN KINERJA KEPEMUDAAN'
					OR jabatan='KEPALA SUBBAGIAN EVALUASI DAN PENILAIAN KINERJA PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN SUMBER DAYA MANUSIA APARATUR') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN SUMBER DAYA APARATUR' OR jabatan='KEPALA SUBBAGIAN MUTASI DAN KEPANGKATAN SUMBER DAYA MANUSIA APARATUR'
					OR jabatan='KEPALA SUBBAGIAN PENGEMBANGAN SUMBER DAYA MANUSIA APARATUR'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN ORGANISASI, TATA LAKSANA DAN KERJASAMA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN ORGANISASI' OR jabatan='KEPALA SUBBAGIAN TATA LAKSANA' OR jabatan='KEPALA SUBBAGIAN KERJASAMA ANTAR LEMBAGA'")
					->get();
				//OR jabatan=''
			} elseif ($jabatan == 'KEPALA BIRO KEUANGAN DAN RUMAH TANGGA') {
				$q = $q->where("jabatan='KEPALA BAGIAN KEUANGAN' or jabatan='KEPALA BAGIAN VERIFIKASI PELAKSANAAN ANGGARAN' OR jabatan='KEPALA BAGIAN PERLENGKAPAN DAN PENGELOLAAN BARANG MILIK NEGARA'
					OR jabatan='KEPALA BAGIAN RUMAH TANGGA'")
					->get();
				//OR jabatan=''
			} elseif ($jabatan == 'KEPALA BAGIAN KEUANGAN') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN KAS DAN PEMBAYARAN' OR jabatan='KEPALA SUBBAGIAN AKUNTANSI DAN PELAPORAN' 
					OR jabatan='KEPALA SUBBAGIAN PENGELOLAAN PNBP'")
					->get();
				//OR jabatan=''
			} elseif ($jabatan == 'KEPALA BAGIAN VERIFIKASI PELAKSANAAN ANGGARAN') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN VERIFIKASI PELAKSANAAN ANGGARAN KEOLAHRAGAAN' OR jabatan='KEPALA SUBBAGIAN VERIFIKASI PELAKSANAAN ANGGARAN KEPEMUDAAN'
					OR jabatan='KEPALA SUBBAGIAN VERIFIKASI PELAKSANAAN ANGGARAN PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERLENGKAPAN DAN PENGELOLAAN BARANG MILIK NEGARA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN LAYANAN PENGADAAN' or jabatan='KEPALA SUBBAGIAN PENGELOLAAN BARANG MILIK NEGARA'
					or jabatan='KEPALA SUBBAGIAN PENGHAPUSAN DAN HIBAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN RUMAH TANGGA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN URUSAN DALAM' or jabatan='KEPALA SUBBAGIAN KEAMANAN DAN KETERTIBAN' 
					or jabatan='KEPALA SUBBAGIAN PERJALANAN DINAS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIRO HUMAS DAN HUKUM') {
				$q = $q->where("jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT' or jabatan='KEPALA BAGIAN SISTEM INFORMASI' or jabatan='KEPALA BAGIAN HUKUM'
					or jabatan='KEPALA BAGIAN TATA USAHA'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUBUNGAN MASYARAKAT') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PELIPUTAN DAN PUBLIKASI' or jabatan='KEPALA SUBBAGIAN DOKUMENTASI DAN PERPUSTAKAAN'
					or jabatan='KEPALA SUBBAGIAN KOMUNIKASI DAN KEMITRAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN SISTEM INFORMASI') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PENGEMBANGAN DAN KEAMANAN SISTEM INFORMASI' or jabatan='KEPALA SUBBAGIAN PENGELOLA INFORMASI'
					or jabatan='KEPALA SUBBAGIAN SISTEM JARINGAN DAN PIRANTI KERAS'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUKUM') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERATURAN PERUNDANG-UNDANGAN' or jabatan='KEPALA SUBBAGIAN PERJANJIAN HUKUM'
					or jabatan='KEPALA SUBBAGIAN LAYANAN HUKUM'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN TATA USAHA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERSURATAN DAN ARSIP' or jabatan='KEPALA SUBBAGIAN KEPROTOKOLAN' or jabatan='KEPALA SUBBAGIAN TU MENTERI'
					or jabatan='KEPALA SUBBAGIAN TU SESMEN' or jabatan='KEPALA SUBBAGIAN TU STAF AHLI'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PEMBERDAYAAN PEMUDA') {
				$q = $q->where("jabatan='SEKRETARIS DEPUTI BIDANG PEMBERDAYAAN PEMUDA' or jabatan='ASISTEN DEPUTI TENAGA DAN PENINGKATAN SUMBER DAYA PEMUDA'
					or jabatan='ASISTEN DEPUTI PENINGKATAN WAWASAN PEMUDA' or jabatan='ASISTEN DEPUTI PENINGKATAN KAPASITAS PEMUDA' or jabatan='ASISTEN DEPUTI PENINGKATAN IPTEK DAN IMTAK PEMUDA'
					or jabatan='ASISTEN DEPUTI PENINGKATAN KREATIVITAS PEMUDA'")
					->get();
			} elseif ($jabatan == 'SEKRETARIS DEPUTI BIDANG PEMBERDAYAAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP' or jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN' or jabatan='KEPALA SUBBAGIAN SUMBER DAYA MANUSIA APARATUR DAN ARSIP'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUBUNGAN MASYARAKAT') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN HUBUNGAN MASYARAKAT DAN SISTEM INFORMASI' or jabatan='KEPALA SUBBAGIAN HUKUM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI TENAGA DAN PENINGKATAN SUMBER DAYA PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PENGKAJIAN TENAGA DAN SUMBER DAYA PEMUDA' or jabatan='KEPALA BIDANG TENAGA KEPEMUDAAN FORMAL DAN NONFORMAL'
					or jabatan='KEPALA BIDANG TENAGA KEPEMUDAAN LAYANAN KHUSUS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGKAJIAN TENAGA DAN SUMBER DAYA PEMUDA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGKAJIAN TENAGA PEMUDA' or jabatan='KEPALA SUBBIDANG PENGKAJIAN SUMBER DAYA PEMUDA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG TENAGA KEPEMUDAAN FORMAL DAN NONFORMAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG FORMAL' or jabatan='KEPALA SUBBIDANG NONFORMAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG TENAGA KEPEMUDAAN LAYANAN KHUSUS') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG DIFABEL' or jabatan='KEPALA SUBBIDANG KEMAMPUAN KHUSUS'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN WAWASAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG WAWASAN POLITIK, PERTAHANAN DAN KEAMANAN' or jabatan='KEPALA BIDANG WAWASAN LINGKUNGAN STRATEGIS DAN PENCEGAHAN BAHAYA DESTRUKTIF'
					or jabatan='KEPALA BIDANG WAWASAN SOSIAL, BUDAYA DAN HUKUM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG WAWASAN POLITIK, PERTAHANAN DAN KEAMANAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG WAWASAN POLITIK DAN PERTAHANAN' or jabatan='KEPALA SUBBIDANG PERTAHANAN DAN KEAMANAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG WAWASAN LINGKUNGAN STRATEGIS DAN PENCEGAHAN BAHAYA DESTRUKTIF') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG WAWASAN LINGKUNGAN STRATEGIS' or jabatan='KEPALA SUBBIDANG PENCEGAHAN BAHAYA DESTRUKTIF'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG WAWASAN SOSIAL, BUDAYA DAN HUKUM') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG WAWASAN SOSIAL DAN BUDAYA' or jabatan='KEPALA SUBBIDANG WAWASAN HUKUM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN KAPASITAS PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PARIWISATA DAN KEMARITIMAN' or jabatan='KEPALA BIDANG INDUSTRI DAN KEMANDIRIAN EKONOMI'
					or jabatan='KEPALA BIDANG KEDAULATAN PANGAN, ENERGI DAN LINGKUNGAN HIDUP'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PARIWISATA DAN KEMARITIMAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PARIWISATA' or jabatan='KEPALA SUBBIDANG MARITIM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG INDUSTRI DAN KEMANDIRIAN EKONOMI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMAHAMAN INDUSTRI' or jabatan='KEPALA SUBBIDANG KEMANDIRIAN EKONOMI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEDAULATAN PANGAN, ENERGI DAN LINGKUNGAN HIDUP') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KEDAULATAN PANGAN DAN ENERGI' or jabatan='KEPALA SUBBIDANG LINGKUNGAN HIDUP'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN IPTEK DAN IMTAK PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PEMETAAN DAN PENELUSURAN IPTEK' or jabatan='KEPALA BIDANG PEMANFAATAN IPTEK'
					or jabatan='KEPALA SUBBIDANG PENGAMALAN IMTAK'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMETAAN DAN PENELUSURAN IPTEK') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENELUSURAN IPTEK' or jabatan='KEPALA SUBBIDANG PEMETAAN IPTEK")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMANFAATAN IPTEK') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG TEKNOLOGI TEPAT GUNA' or jabatan='KEPALA SUBBIDANG TEKNOLOGI INDUSTRI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGHAYATAN DAN PENGAMALAN IMTAK') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGHAYATAN IMTAK' or jabatan='KEPALA SUBBIDANG PENGAMALAN IMTAK'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN KREATIVITAS PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG KREATIVITAS GRAFIKA DAN KRIYA' or jabatan='KEPALA BIDANG KREATIVITAS FASHION DAN FILM'
					or jabatan='KEPALA BIDANG KREATIVITAS TEKNOLOGI INFORMASI' or jabatan='KEPALA BIDANG KREATIVITAS MUSIK DAN KULINER'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS GRAFIKA DAN KRIYA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG GRAFIKA' or jabatan='KEPALA SUBBIDANG KRIYA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS GRAFIKA DAN KRIYA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG GRAFIKA' or jabatan='KEPALA SUBBIDANG KRIYA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS FASHION DAN FILM') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG FASHION' or jabatan' or jabatan='KEPALA SUBBIDANG FILM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS TEKNOLOGI INFORMASI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PIRANTI LUNAK' or jabatan='KEPALA SUBBIDANG PERANGKAT KERAS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KREATIVITAS MUSIK DAN KULINER') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG MUSIK' or jabatan='KEPALA SUBBIDANG KULINER'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PENGEMBANGAN PEMUDA') {
				$q = $q->where("jabatan='ASISTEN DEPUTI KEPEMINPINAN DAN KEPELOPORAN PEMUDA' or jabatan='ASISTEN DEPUTI KEWIRAUSAHAAN PEMUDA'
					or jabatan='ASISTEN DEPUTI ORGANISASI KEPEMUDAAN DAN KEPRAMUKAAN' or jabatan='ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR PEMUDA'
					or jabatan='ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA' or jabatan='SEKRETARIS DEPUTI BIDANG PENGEMBANGAN PEMUDA'")
					->get();
			} elseif ($jabatan == 'SEKRETARIS DEPUTI BIDANG PENGEMBANGAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP' or jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT, HUKUM, DAN SISTEM INFORMASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN' or jabatan='KEPALA SUBBAGIAN SUMBER DAYA MANUSIA APARATUR DAN ARSIP'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEPEMINPINAN DAN KEPELOPORAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG KADERISASI DAN PENDAYAGUNAAN KEPEMIMPINAN' or jabatan='KEPALA BIDANG KEPELOPORAN TANGGAP BENCANA DAN RAWAN SOSIAL'
					or jabatan='KEPALA BIDANG KEPELOPORAN DESA DAN DAERAH KHUSUS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KADERISASI DAN PENDAYAGUNAAN KEPEMIMPINAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KADERISASI' or jabatan='KEPALA SUBBIDANG PENDAYAGUNAAN KEPEMIMPINAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEPELOPORAN TANGGAP BENCANA DAN RAWAN SOSIAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG TANGGAP BENCANA' or jabatan='KEPALA SUBBIDANG RAWAN SOSIAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEPELOPORAN DESA DAN DAERAH KHUSUS') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN DESA' or jabatan='KEPALA SUBBIDANG DAERAH TERLUAR DAN TERTINGGAL'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEWIRAUSAHAAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG PENELUSURAN DAN PEMETAAN POTENSI KEWIRAUSAHAAN PEMUDA' or jabatan='KEPALA BIDANG PENDAMPINGAN DAN PENGEMBANGAN POTENSI'
					or jabatan='KEPALA BIDANG AKSES PERMODALAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENELUSURAN DAN PEMETAAN POTENSI KEWIRAUSAHAAN PEMUDA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENELUSURAN' or jabatan='KEPALA SUBBIDANG PEMETAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENDAMPINGAN DAN PENGEMBANGAN POTENSI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENDAMPINGAN' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN POTENSI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG AKSES PERMODALAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG FASILITAS PERMODALAN' or jabatan='KEPALA SUBBIDANG FASILITAS KELEMBAGAAN LPKP'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI ORGANISASI KEPEMUDAAN DAN KEPRAMUKAAN') {
				$q = $q->where("jabatan='KEPALA BIDANG ORGANISASI KEPELAJARAN' or jabatan='KEPALA BIDANG ORGANISASI KEMAHASISWAAN' 
					or jabatan='KEPALA BIDANG ORGANISASI KEPEMUDAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEPELAJARAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INTRA BIDANG ORGANISASI KEPELAJARAN' or jabatan='KEPALA SUBBAGIAN EXTRA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEMAHASISWAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INTRA BIDANG ORGANISASI KEMAHASISWAAN' or jabatan='KEPALA SUBBAGIAN EXTRA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEPEMUDAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INTRA BIDANG ORGANISASI KEPEMUDAAN' or jabatan='KEPALA SUBBAGIAN EXTRA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR PEMUDA') {
				$q = $q->where("jabatan='KEPALA BIDANG STANDARISASI ORGANISASI DAN SARANA KEPEMUDAAN' or jabatan='KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TIMUR'
					or jabatan='KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TENGAH' or jabatan='KEPALA BIDANG PRASARANA DAN SARANA INDONESIA BARAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG STANDARISASI ORGANISASI DAN SARANA KEPEMUDAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PENDIDIKAN' or jabatan='KEPALA SUBBIDANG ORGANISASI KEPEMUDAAN'
					or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PRESTASI' or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA REKREASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TIMUR') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA INDONESIA TIMUR' or jabatan='KEPALA SUBBIDANG PRASARANA INDONESIA TIMUR'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA INDONESIA TENGAH') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA INDONESIA TENGAH' or jabatan='KEPALA SUBBIDANG PRASARANA INDONESIA TENGAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA INDONESIA BARAT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA INDONESIA BARAT' or jabatan='KEPALA SUBBIDANG PRASARANA INDONESIA BARAT'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG KEMITRAAN DALAM NEGERI' or jabatan='KEPALA BIDANG KEMITRAAN LUAR NEGERI'
					or jabatan='KEPALA BIDANG PROMOSI DAN PENGHARGAAN KEPEMUDAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEMITRAAN DALAM NEGERI') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN KEMITRAAN PUSAT DAN DAERAH' or jabatan='KEPALA SUBBIDANG KEMITRAAN LINTAS SEKTOR DAN SWASTA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEMITRAAN LUAR NEGERI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG BILATERAL' or jabatan='KEPALA SUBBIDANG MULTILATERAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PROMOSI DAN PENGHARGAAN KEPEMUDAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PROMOSI KEPEMUDAAN' or jabatan='KEPALA SUBBIDANG PENGHARGAAN KEPEMUDAAN'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PEMBUDAYAAN OLAHRAGA') {
				$q = $q->where("jabatan='ASISTEN DEPUTI PENGELOLAAN OLAHRAGA PENDIDIKAN' or jabatan='ASISTEN DEPUTI PENGELOLAAN OLAHRAGA REKREASI'
					or jabatan='ASISTEN DEPUTI PENGELOLAAN PEMBINAAN SENTRA DAN SEKOLAH KHUSUS OLAHRAGA' or jabatan='ASISTEN DEPUTI PENGEMBANGAN OLAHRAGA TRADISIONAL DAN LAYANAN KHUSUS'
					or jabatan='ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGELOLAAN OLAHRAGA PENDIDIKAN') {
				$q = $q->where("jabatan='KEPALA BIDANG OLAHRAGA PENDIDIKAN DASAR' or jabatan='KEPALA BIDANG OLAHRAGA PENDIDIKAN MENENGAH'
					or jabatan='KEPALA BIDANG OLAHRAGA PENDIDIKAN TINGGI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENDIDIKAN DASAR') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN BIDANG OLAHRAGA PENDIDIKAN DASAR' or jabatan='KEPALA SUBBIDANG KOMPETISI BIDANG OLAHRAGA PENDIDIKAN DASAR'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENDIDIKAN MENENGAH') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN BIDANG OLAHRAGA PENDIDIKAN MENENGAH' or jabatan='KEPALA SUBBIDANG KOMPETISI BIDANG OLAHRAGA PENDIDIKAN MENENGAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENDIDIKAN TINGGI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN BIDANG OLAHRAGA PENDIDIKAN TINGGI' or jabatan='KEPALA SUBBIDANG KOMPETISI BIDANG OLAHRAGA PENDIDIKAN TINGGI'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGELOLAAN OLAHRAGA REKREASI') {
				$q = $q->where("jabatan='KEPALA BIDANG PEMBINAAN OLAHRAGA MASSAL DAN KESEHATAN OLAHRAGA' or jabatan='KEPALA BIDANG PENGEMBANGAN SANGGAR DAN PUSAT KEBUGARAN'
					or jabatan='KEPALA BIDANG PENGELOLAAN OLAHRAGA PETUALANGAN, TANTANGAN DAN WISATA' or jabatan='KEPALA BIDANG PENGEMBANGAN RUANG PUBLIK OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMBINAAN OLAHRAGA MASSAL DAN KESEHATAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN OLAHRAGA MASSAL' or jabatan='KEPALA SUBBIDANG KESEHATAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGEMBANGAN SANGGAR DAN PUSAT KEBUGARAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN SANGGAR OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PUSAT KEBUGARAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGELOLAAN OLAHRAGA PETUALANGAN, TANTANGAN DAN WISATA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN OLAHRAGA PETUALANGAN DAN TANTANGAN' or jabata='KEPALA SUBBIDANG PENGELOLAAN OLAHRAGA WISATA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGEMBANGAN RUANG PUBLIK OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN RUANG PUBLIK OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGKAJIAN RUANG PUBLIK OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGELOLAAN PEMBINAAN SENTRA DAN SEKOLAH KHUSUS OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG SENTRA DAN PERKUMPULAN OLAHRAGA' or jabatan='KEPALA BIDANG SEKOLAH KHUSUS OLAHRAGA'
					or jabatan='KEPALA BIDANG PEMBINAAN PPLP' or jabatan='KEPALA BIDANG PEMBINAAN PPLM'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SENTRA DAN PERKUMPULAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN SENTRA DAN PERKUMPULAN OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN SENTRA DAN PERKUMPULAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SEKOLAH KHUSUS OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN SEKOLAH KHUSUS OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN SEKOLAH KHUSUS OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMBINAAN PPLP') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN PPLP' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PPLP'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMBINAAN PPLM') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN PPLM' or jabatan='KEPALA SUBBIDANG PEMBINAAN PPLM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENGEMBANGAN OLAHRAGA TRADISIONAL DAN LAYANAN KHUSUS') {
				$q = $q->where("jabatan='KEPALA BIDANG OLAHRAGA TRADISIONAL' or jabatan='KEPALA BIDANG OLAHRAGA USIA DINI, LANJUT USIA DAN OLAHRAGA KHUSUS'
					or jabatan='KEPALA BIDANG OLAHRAGA PENYANDANG CACAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA TRADISIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGKAJIAN OLAHRAGA TRADISIONAL' or jabatan='KEPALA SUBBIDANG PENGELOLAAN OLAHRAGA TRADISIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA USIA DINI, LANJUT USIA DAN OLAHRAGA KHUSUS') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN OLAHRAGA USIA DINI DAN LANJUT USIA' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN OLAHRAGA KHUSUS'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PENYANDANG CACAT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMBINAAN OLAHRAGA PENYANDANG CACAT' or jabatan='KEPALA SUBBIDANG KOMPETISI OLAHRAGA PENYANDANG CACAT'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI KEMITRAAN DAN PENGHARGAAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG KEMITRAAN DALAM NEGERI DAN LUAR NEGERI' or jabatan='KEPALA BIDANG BIMBINGAN DAN PENGEMBANGAN KARIER ATLIT'
					or jabatan='KEPALA BIDANG PENGHARGAAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KEMITRAAN DALAM NEGERI DAN LUAR NEGERI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KEMITRAAN DALAM NEGERI' or jabatan='KEPALA SUBBIDANG KEMITRAAN LUAR NEGERI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG BIMBINGAN DAN PENGEMBANGAN KARIER ATLIT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG BIMBINGAN' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN KARIER'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGHARGAAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENELUSURAN PENGHARGAAN OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENYELENGGARAAN PENGHARGAAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'DEPUTI BIDANG PENINGKATAN PRESTASI OLAHRAGA') {
				$q = $q->where("jabatan='SEKRETARIS DEPUTI BIDANG PENINGKATAN PRESTASI OLAHRAGA' or jabatan='ASISTEN DEPUTI PEMBIBITAN DAN IPTEK OLAHRAGA'
					or jabatan='ASISTEN DEPUTI PENINGKATAN TENAGA DAN ORGANISASI KEOLAHRAGAAN' or jabatan='ASISTEN DEPUTI INDUSTRI DAN PROMOSI OLAHRAGA'
					or jabatan='ASISTEN DEPUTI OLAHRAGA PRESTASI' or jabatan='ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'SEKRETARIS DEPUTI BIDANG PENINGKATAN PRESTASI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP' or jabatan='KEPALA BAGIAN HUBUNGAN MASYARAKAT, HUKUM, DAN SISTEM INFORMASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN PERENCANAAN , SUMBER DAYA MANUSIA APARATUR DAN ARSIP') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN PERENCANAAN' or jabatan='KEPALA SUBBAGIAN SUMBER DAYA MANUSIA APARATUR DAN ARSIP'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN HUBUNGAN MASYARAKAT, HUKUM, DAN SISTEM INFORMASI') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN HUBUNGAN MASYARAKAT DAN SISTEM INFORMASI' or jabatan='KEPALA SUBBAGIAN HUKUM'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PEMBIBITAN DAN IPTEK OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG PEMANDUAN DAN PENGEMBANGAN BAKAT' or jabatan='KEPALA BIDANG KOMPETISI USIA MUDA'
					or jabatan='KEPALA BIDANG PENGEMBANGAN IPTEK OLAHRAGA' or jabatan='KEPALA BIDANG PEMANFAATAN IPTEK OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMANDUAN DAN PENGEMBANGAN BAKAT') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEMANDUAN BAKAT' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN BAKAT'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG KOMPETISI USIA MUDA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG KOMPETISI DAERAH DAN NASIONAL' or jabatan='KEPALA SUBBIDANG KOMPETISI INTERNASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGEMBANGAN IPTEK OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN ILMU PENGETAHUAN KEOLAHRAGAAN' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN TEKNOLOGI KEOLAHRAGAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PEMANFAATAN IPTEK OLAHRAGA') {
				$q = $q->where("jabatan='EPALA SUBBIDANG DISEMINASI' or jabatan='KEPALA SUBBIDANG PENERAPAN'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI PENINGKATAN TENAGA DAN ORGANISASI KEOLAHRAGAAN') {
				$q = $q->where("jabatan='KEPALA BIDANG PENINGKATAN MUTU PELATIH DAN INSTRUKTUR' or jabatan='KEPALA BIDANG PENINGKATAN MUTU WASIT, JURI DAN TENAGA PENDUKUNG'
					or jabatan='KEPALA BIDANG ORGANISASI KEOLAHRAGAAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENINGKATAN MUTU PELATIH DAN INSTRUKTUR') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU PELATIH' or jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU INSTRUKTUR'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENINGKATAN MUTU WASIT, JURI DAN TENAGA PENDUKUNG') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU WASIT DAN JURI' or jabatan='KEPALA SUBBIDANG PENINGKATAN MUTU TENAGA PENDUKUNG'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG ORGANISASI KEOLAHRAGAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGELOLAAN INDUK ORGANISASI CABANG OLAHRAGA' or jabatan='KEPALA SUBBIDANG PENGELOLAAN ORGANISASI FUNGSIONAL DAN PROFESIONAL'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI INDUSTRI DAN PROMOSI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG PRODUK BARANG DAN JASA INDUSTRI OLAHRAGA' or jabatan='KEPALA SUBBIDANG INVENTARISASI INDUSTRI OLAHRAGA'
					or jabatan='KEPALA BIDANG PROMOSI DAN PEMASARAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PRODUK BARANG DAN JASA INDUSTRI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PRODUK BARANG INDUSTRI OLAHRAGA' or jabatan='KEPALA SUBBIDANG PRODUK JASA INDUSTRI OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA SUBBIDANG INVENTARISASI INDUSTRI OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG INVENTARISASI INDUSTRI OLAHRAGA' or jabatan='KEPALA SUBBIDANG MANAJEMEN INDUSTRI OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PROMOSI DAN PEMASARAN OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PROMOSI OLAHRAGA' or jabatan='KEPALA SUBBIDANG PEMASARAN OLAHRAGA'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI OLAHRAGA PRESTASI') {
				$q = $q->where("jabatan='KEPALA BIDANG OLAHRAGA PRESTASI DAERAH' or jabatan='KEPALA BIDANG OLAHRAGA PRESTASI NASIONAL'
					or jabatan='KEPALA BIDANG OLAHRAGA PRESTASI INTERNASIONAL' or jabatan='KEPALA BIDANG PENGELOLAAN PEMUSATAN PELATIHAN OLAHRAGA NASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PRESTASI DAERAH') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN PRESTASI DAERAH' or jabatan='KEPALA SUBBIDANG PEKAN DAN KEJUARAAN OLAHRAGA PRESTASI DAERAH'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PRESTASI NASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEKAN DAN KEJUARAAN OLAHRAGA PRESTASI NASIONAL' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PRESTASI NASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG OLAHRAGA PRESTASI INTERNASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PEKAN DAN KEJUARAAN OLAHRAGA PRESTASI INTERNASIONAL' or jabatan='KEPALA SUBBIDANG PENGEMBANGAN PRESTASI INTERNASIONAL'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG PENGELOLAAN PEMUSATAN PELATIHAN OLAHRAGA NASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PENGEMBANGAN ATLET ANDALAN NASIONAL' or jabatan='KEPALA SUBBIDANG TATA KELOLA KONTINGEN'")
					->get();
			} elseif ($jabatan == 'ASISTEN DEPUTI STANDARISASI DAN INFRASTRUKTUR OLAHRAGA') {
				$q = $q->where("jabatan='KEPALA BIDANG STANDARISASI, AKREDITASI, DAN SERTIFIKASI KEOLAHRAGAAN' or jabatan='KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PENDIDIKAN'
					or jabatan='KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA REKREASI' or jabatan='KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PRESTASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG STANDARISASI, AKREDITASI, DAN SERTIFIKASI KEOLAHRAGAAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG STANDARISASI' or jabatan='KEPALA SUBBIDANG AKREDITASI DAN SERTIFIKASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PENDIDIKAN') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PENDIDIKAN' or jabatan='KEPALA SUBBIDANG PRASARANA OLAHRAGA PENDIDIKAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA REKREASI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PRASARANA OLAHRAGA REKREASI' or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA REKREASI'")
					->get();
			} elseif ($jabatan == 'KEPALA BIDANG SARANA DAN PRASARANA OLAHRAGA PRESTASI') {
				$q = $q->where("jabatan='KEPALA SUBBIDANG PRASARANA OLAHRAGA PRESTASI' or jabatan='KEPALA SUBBIDANG SARANA OLAHRAGA PRESTASI'")
					->get();
			// Mei 2020		
			}elseif ($jabatan == 'INSPEKTUR') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN TATA USAHA INSPEKTORAT'")
					->get();
			}elseif ($jabatan == 'KEPALA PUSAT PENGEMBANGAN ILMU PENGETAHUAN DAN TEKNOLOGI, DAN KESEHATAN OLAHRAGA NASIOANAL') {
				$q = $q->where("jabatan='KEPALA BAGIAN TATA USAHA' or jabatan='KEPALA BIDANG ANTROPOMETRI DAN KAPASITAS FISIK' or jabatan='KEPALA BIDANG BIOMEKANIK DAN KEBUGARAN JASMANI' or jabatan='KEPALA BIDANG KESEHATAN OLAHRAGAWAN'")
					->get();
			} elseif ($jabatan == 'KEPALA BAGIAN TATA USAHA') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN KEPEGAWAIAN DAN KEUANGAN' or jabatan='KEPALA SUBBAGIAN UMUM'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG ANTROPOMETRI DAN KAPASITAS FISIK') {
				$q = $q->where("jabatan='KEPALA SEKSI ANTROPOMETRI DAN GIZI' or jabatan='KEPALA SEKSI KAPASITAS FISIK'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG BIOMEKANIK DAN KEBUGARAN JASMANI') {
				$q = $q->where("jabatan='KEPALA SEKSI BIOMEKANIK' or jabatan='KEPALA SEKSI KEBUGARAN JASMANI'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG KESEHATAN OLAHRAGAWAN') {
				$q = $q->where("jabatan='KEPALA SEKSI MEDIS' or jabatan='KEPALA SEKSI REHABILITASI DAN FISIOTERAPI'")
					->get();
			}elseif ($jabatan == 'KEPALA PPPON') {
				$q = $q->where("jabatan='KEPALA BAGIAN TU PPPON' or jabatan='KEPALA BIDANG PRASARANA DAN SARANA TEKNIS PPPON' or jabatan='KEPALA BIDANG PENYELENGGARAAN PEMUDA PPPON' or jabatan='KEPALA BIDANG PENYELENGGARAAN OLAHRAGA PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BAGIAN TU PPPON') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN UMUM DAN KEPEGAWAIAN PPPON' or jabatan='KEPALA SUBBAGIAN KEUANGAN DAN EVALUASI PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG PRASARANA DAN SARANA TEKNIS PPPON') {
				$q = $q->where("jabatan='KEPALA SEKSI PRASARANA TEKNIS PPPON' or jabatan='KEPALA SEKSI SARANA TEKNIS PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG PENYELENGGARAAN PEMUDA PPPON') {
				$q = $q->where("jabatan='KEPALA SEKSI PROGRAM PPPON' or jabatan='KEPALA SEKSI EVALUASI PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA BIDANG PENYELENGGARAAN OLAHRAGA PPPON') {
				$q = $q->where("jabatan='KEPALA SEKSI PROGRAM DAN EVALUASI PENYELENGGARAAN OLAHRAGA PPPON' or jabatan='KEPALA SEKSI SARANA TEKNIS PPPON'")
					->get();
			}elseif ($jabatan == 'KEPALA MUSEUM OLAHRAGA NASIONAL') {
				$q = $q->where("jabatan='KEPALA SUBBAGIAN TATA USAHA' or jabatan='KEPALA SEKSI PAMERAN DAN EDUKASI' or jabatan='KEPALA SEKSI KOLEKSI DAN DOKUMENTASI'")
					->get();
			} else {
				$q = $q->get();
			}


			return $q->result_array();
		}
		public function select_PenerimaDinas()
		{
			$q = $this->db
				->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat, j.id_satuan_kerja, nama_unit, id_jabatan, jabatan')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id ', 'left')
				->join('tb_satuan_kerja as sk', 'j.id_satuan_kerja = sk.id ', 'left')
				->join('tb_user as u', 'u.id_pegawai = p.id ', 'left')
				->where('u.id_grup > 3')
				->where("p.id != '" . $this->session->userdata('id') . "'")
				// ->where("sk.dinas = '1'")
				->where("p.level >= '" . $this->session->userdata('level') . "'")
				->where("p.level < '10'")
				->get();


			return $q->result_array();
		}
		// public function select_PenerimaNonDinas()
		// {
		//     $q = $this->db
		//         ->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat, id_satuan_kerja, nama_unit, jabatan_non_dinas, jabatan_dinas')
		//         ->from('tb_pegawai as p')
		//         ->join('tb_satuan_kerja as sk', 'p.id_satuan_kerja = sk.id ', 'left')
		//         ->where("sk.dinas = '0'")
		//         ->where("p.level >= '" . $this->session->userdata('level') . "'")
		//         ->where("p.level < '10'")
		//         ->get();


		//     return $q->result_array();
		// }
		public function select_all()
		{
			$q = $this->db
				->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat, id_satuan_kerja, nama_unit, id_jabatan, j.jabatan, sk.nama_unit, u.id_grup')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id')
				->join('tb_satuan_kerja as sk', 'j.id_satuan_kerja = sk.id ', 'left')
				->join('tb_user as u', 'u.id_pegawai = p.id')
				->where("u.id_grup > 2")
				->order_by('nama_lengkap', 'asc')
				->get();


			return $q->result_array();
		}
		public function Select_PegawaiById($id)
		{

			$q = $this->db
				->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat, 
                id_satuan_kerja, nama_unit, p.id_jabatan,level,
                telp, jenis_kelamin, golongan, agama, tempat_lahir, tgl_lahir')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id')
				->join('tb_satuan_kerja as sk', 'j.id_satuan_kerja = sk.id ')
				->where("p.id = '" . $id . "'")
				->get();


			return $q->result_array();
		}
		public function Select_PegawaiBySatuanKerja($id)
		{

			$q = $this->db
				->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat, 
                id_satuan_kerja, nama_unit, p.id_jabatan,level, nama_unit
                telp, jenis_kelamin, golongan, agama, tempat_lahir, tgl_lahir')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id')
				->join('tb_satuan_kerja as sk', 'j.id_satuan_kerja = sk.id ')
				->order_by('p.level', 'ASC')
				->where("sk.id = '" . $id . "'")
				->get();


			return $q->result_array();
		}
		public function Select_PegawaiBySatuanKerjaLv($id, $lv)
		{

			$q = $this->db
				->select('p.id as id_pegawai, nip, nama_lengkap, nama_singkat, alamat, 
                id_satuan_kerja, nama_unit, p.id_jabatan, j.jabatan, level, nama_unit
                telp, jenis_kelamin, golongan, agama, tempat_lahir, tgl_lahir')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id')
				->join('tb_satuan_kerja as sk', 'j.id_satuan_kerja = sk.id ')
				->order_by('p.nama_lengkap', 'ASC')
				->where("sk.id = '" . $id . "'")
				->where("p.level = '" . $lv . "'")
				->get();


			return $q->result_array();
		}
		public function select()
		{
			$q = $this->db
				->select('p.id,p.nip,p.nama_lengkap,p.nama_singkat,p.alamat,p.telp,
                p.jenis_kelamin,p.golongan,p.agama,p.tempat_lahir,p.tgl_lahir,j.id_satuan_kerja,
               p.id_jabatan,j.jabatan,p.level,sk.id as id_sk,sk.nama_unit')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'j.id=p.id_jabatan')
				->join('tb_satuan_kerja as sk', 'sk.id=j.id_satuan_kerja')
				->where("NOT (level = '0')")
				->get();


			return $q->result_array();
		}
		public function select_BelumAdaAkun()
		{
			$q = $this->db
				->select('p.id,p.nip,p.nama_lengkap,p.nama_singkat,p.alamat,p.telp,
                p.jenis_kelamin,p.golongan,p.agama,p.tempat_lahir,p.tgl_lahir,j.id_satuan_kerja,
                p.level,sk.id as id_sk,sk.nama_unit,j.jabatan')
				->from('tb_pegawai as p')
				->join('tb_jabatan as j', 'p.id_jabatan = j.id')
				->join('tb_satuan_kerja as sk', 'sk.id=j.id_satuan_kerja')
				->join('tb_user as u', 'u.id_pegawai=p.id', 'left')
				->where("NOT (level = '0') AND u.id_pegawai IS NULL")
				->get();


			return $q->result_array();
		}

		public function add($data)
		{
			$this->db->insert('tb_pegawai', $data);
		}
		public function update($data, $id)
		{
			$this->db->where('id', $id);
			$this->db->update('tb_pegawai', $data);
		}
		public function del($id)
		{

			if ($this->db->delete('tb_pegawai', array('id' => $id))) {

				return true;
			} else {
				return false;
			}
		}
	}
